language: ruby
rvm:
- 2.4.1
bundler_args: --jobs=2
cache: bundler
services:
  - postgresql
before_script:
  - cp config/database.travis.yml config/database.yml
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - psql -c 'create database letsdev_test' -U postgres
script:
  - bundle exec rake spec
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi
