default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  host: localhost
  username: LetsDev
  password: <%= ENV['LETS_DEV_DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: LetsDev_development

test:
  <<: *default
  database: LetsDev_test

production:
  <<: *default
  database: LetsDev_production
