default: &default
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  url: <%= ENV['LETS_DEV_DATABASE_URL'] %>

test:
  <<: *default
  url: <%= ENV['LETS_DEV_DATABASE_URL'] %>
  database: letsdev_test
  port: 5462
  
staging:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: letsdev_staging

production:
  <<: *default
  database: letsdev_production
